import logging

logger = logging.getLogger(__name__)

"""
Source of Country name list: https://prod.trackmania.core.nadeo.online/zones/
Postprocessed to find all entries which were children of children of "World".
Then associated with a 2 letter code manually using an online list.
"""
CountryCodes = {
	"Afghanistan": "AF",
	"Albania": "AL",
	"Algeria": "DZ",
	"Andorra": "AD",
	"Angola": "AO",
	"Antigua and Barbuda": "AG",
	"Argentina": "AR",
	"Armenia": "AM",
	"Australia": "AU",
	"Austria": "AT",
	"Azerbaijan": "AZ",
	"Bahamas": "BS",
	"Bahrain": "BH",
	"Bangladesh": "BD",
	"Barbados": "BB",
	"Belarus": "BY",
	"Belgium": "BE",
	"Belize": "BZ",
	"Benin": "BJ",
	"Bhutan": "BT",
	"Bolivia": "BO",
	"Bosnia and Herzegovina": "BA",
	"Botswana": "BW",
	"Brazil": "BR",
	"Brunei": "BN",
	"Bulgaria": "BG",
	"Burkina Faso": "BF",
	"Burundi": "BI",
	"Cambodia": "KH",
	"Cameroon": "CM",
	"Canada": "CA",
	"Cabo Verde": "CV",
	"Central African Republic": "CF",
	"Chad": "TD",
	"Chile": "CL",
	"China": "CN",
	"Colombia": "CO",
	"Comoros": "KM",
	"Congo": "CG",
	"Costa Rica": "CR",
	"Croatia": "HR",
	"Cuba": "CU",
	"Cyprus": "CY",
	"Czechia": "CZ",
	"Denmark": "DK",
	"Djibouti": "DJ",
	"Dominica": "DM",
	"Dominican Republic": "DO",
	"DR Congo": "CD",
	"Ecuador": "EC",
	"Egypt": "EG",
	"El Salvador": "SV",
	"Equatorial Guinea": "GQ",
	"Eritrea": "ER",
	"Estonia": "EE",
	"Ethiopia": "ET",
	"Fiji": "FJ",
	"Finland": "FI",
	"France": "FR",
	"Gabon": "GA",
	"Georgia": "GE",
	"Germany": "DE",
	"Ghana": "GH",
	"Greece": "GR",
	"Grenada": "GD",
	"Guatemala": "GT",
	"Guinea": "GN",
	"Guinea-Bissau": "GW",
	"Guyana": "GY",
	"Haiti": "HT",
	"Honduras": "HN",
	"Hong Kong": "HK",
	"Hungary": "HU",
	"Iceland": "IS",
	"India": "IN",
	"Indonesia": "ID",
	"Iran": "IR",
	"Iraq": "IQ",
	"Ireland": "IE",
	"Israel": "IL",
	"Italy": "IT",
	"Ivory Coast": "CI",
	"Jamaica": "JM",
	"Japan": "JP",
	"Jordan": "JO",
	"Kazakhstan": "KZ",
	"Kenya": "KE",
	"Kuwait": "KW",
	"Kyrgyzstan": "KG",
	"Laos": "LA",
	"Latvia": "LV",
	"Lebanon": "LB",
	"Lesotho": "LS",
	"Liberia": "LR",
	"Libya": "LY",
	"Liechtenstein": "LI",
	"Lithuania": "LT",
	"Luxembourg": "LU",
	"North Macedonia": "MK",
	"Madagascar": "MG",
	"Malawi": "MW",
	"Malaysia": "MY",
	"Maldives": "MV",
	"Mali": "ML",
	"Malta": "MT",
	"Marshall Islands": "MH",
	"Mauritania": "MR",
	"Mauritius": "MU",
	"Mexico": "MX",
	"Micronesia": "FM",
	"Moldova": "MD",
	"Monaco": "MC",
	"Mongolia": "MN",
	"Montenegro": "ME",
	"Morocco": "MA",
	"Mozambique": "MZ",
	"Myanmar": "MM",
	"Namibia": "NA",
	"Nauru": "NR",
	"Nepal": "NP",
	"Netherlands": "NL",
	"New Zealand": "NZ",
	"Nicaragua": "NI",
	"Niger": "NE",
	"Nigeria": "NG",
	"North Korea": "KP",
	"Norway": "NO",
	"Oman": "OM",
	"Pakistan": "PK",
	"Palau": "PW",
	"Panama": "PA",
	"Papua New Guinea": "PG",
	"Paraguay": "PY",
	"Peru": "PE",
	"Philippines": "PH",
	"Poland": "PL",
	"Portugal": "PT",
	"Qatar": "QA",
	"Romania": "RO",
	"Russia": "RU",
	"Rwanda": "RW",
	"Saint Kitts and Nevis": "KN",
	"Saint Lucia": "LC",
	"Saint Vincent and the Grenadines": "VC",
	"Samoa": "WS",
	"San Marino": "SM",
	"São Tomé and Príncipe": "ST",
	"Saudi Arabia": "SA",
	"Senegal": "SN",
	"Serbia": "RS",
	"Seychelles": "SC",
	"Sierra Leone": "SL",
	"Singapore": "SG",
	"Slovakia": "SK",
	"Slovenia": "SI",
	"Solomon Islands": "SB",
	"Somalia": "SO",
	"South Africa": "ZA",
	"South Korea": "KR",
	"South Sudan": "SS",
	"Spain": "ES",
	"Sri Lanka": "LK",
	"Sudan": "SD",
	"Suriname": "SR",
	"Sweden": "SE",
	"Switzerland": "CH",
	"Syria": "SY",
	"Taïwan": "TW",
	"Tajikistan": "TJ",
	"Tanzania": "TZ",
	"Thailand": "TH",
	"The Gambia": "GM",
	"Timor-Leste": "TL",
	"Togo": "TG",
	"Tonga": "TO",
	"Trinidad and Tobago": "TT",
	"Tunisia": "TN",
	"Turkey": "TR",
	"Turkmenistan": "TM",
	"Tuvalu": "TV",
	"Uganda": "UG",
	"Ukraine": "UA",
	"United Arab Emirates": "AE",
	"United Kingdom": "GB",
	"United States": "US",
	"Uruguay": "UY",
	"Uzbekistan": "UZ",
	"Vanuatu": "VU",
	"Venezuela": "VE",
	"Vietnam": "VN",
	"Yemen": "YE",
	"Zambia": "ZM",
	"Zimbabwe": "ZW",
}

def get_discord_flag(country: str )-> str:
	if country in CountryCodes:
		return f':flag_{CountryCodes[country].lower()}:'
	logger.error(f"Country not found in CountryCodes lookup: '{country}'")
	return ':globe_with_meridians:'
